# Generated by Django 5.1.4 on 2026-05-02 06:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('bank', models.CharField(blank=True, choices=[('fnb', 'FNB Eswatini'), ('standard', 'Standard Bank'), ('nedbank', 'Nedbank'), ('eswatini_bank', 'Eswatini Bank')], max_length=100)),
                ('bnpl_limit', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('bnpl_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting for Customer'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('bnpl_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('direct_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('used_bnpl', models.BooleanField(default=False)),
                ('bank_used', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='payments.customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='payments.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BNPLLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('instalments', models.IntegerField(default=3)),
                ('instalment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='payments.customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='payments.merchant')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='payments.paymentsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
