# Generated by Django 5.1.4 on 2026-05-04 10:16

import django.db.models.deletion
import payments.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='bnpl_limit',
            new_name='credit_limit',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='bnpl_used',
            new_name='current_balance',
        ),
        migrations.RenameField(
            model_name='paymentsession',
            old_name='used_bnpl',
            new_name='jit_funded',
        ),
        migrations.RemoveField(
            model_name='paymentsession',
            name='bnpl_amount',
        ),
        migrations.RemoveField(
            model_name='paymentsession',
            name='direct_amount',
        ),
        migrations.AddField(
            model_name='customer',
            name='default_funding_mode',
            field=models.CharField(choices=[('kona_credit', 'Kona Credit Card'), ('bank', 'Bank Account (EPS)')], default='kona_credit', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=24.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='statement_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='funding_mode',
            field=models.CharField(blank=True, choices=[('credit', 'Kona Credit Card'), ('bank', 'Bank Transfer (EPS)'), ('jit', 'JIT Bank to Card')], max_length=30),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='jit_bank',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(default=payments.models.generate_card_number, max_length=16)),
                ('cvv', models.CharField(default=payments.models.generate_cvv, max_length=3)),
                ('expiry_date', models.DateField(default=payments.models.default_expiry)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('cancelled', 'Cancelled'), ('pending', 'Pending Activation')], default='active', max_length=20)),
                ('bin_country', models.CharField(default='ZA', max_length=50)),
                ('card_network', models.CharField(default='Visa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_details', to='payments.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(default=payments.models.generate_card_number, max_length=16)),
                ('cvv', models.CharField(default=payments.models.generate_cvv, max_length=3)),
                ('expiry_date', models.DateField(default=payments.models.default_expiry)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('cancelled', 'Cancelled'), ('pending', 'Pending Activation')], default='active', max_length=20)),
                ('bin_country', models.CharField(default='ZA', max_length=50)),
                ('card_network', models.CharField(default='Visa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='payments.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CreditStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('interest_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('minimum_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed — Unpaid'), ('paid_minimum', 'Minimum Paid'), ('paid_full', 'Paid in Full'), ('overdue', 'Overdue')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='payments.customer')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('repayment', 'Repayment'), ('interest', 'Interest Charge'), ('fee', 'Fee'), ('refund', 'Refund')], max_length=20)),
                ('funding_mode', models.CharField(blank=True, choices=[('credit', 'Kona Credit'), ('bank', 'Bank Transfer (EPS)'), ('jit', 'JIT Bank to Card')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='payments.customer')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.merchant')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='payments.paymentsession')),
                ('statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.creditstatement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebitMandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank', models.CharField(choices=[('fnb', 'FNB Eswatini'), ('standard', 'Standard Bank'), ('nedbank', 'Nedbank'), ('eswatini_bank', 'Eswatini Bank')], max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('authorised_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='payments.customer')),
            ],
            options={
                'ordering': ['-authorised_at'],
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('eps_transfer', 'EPS Bank Transfer'), ('debit_order', 'Debit Order'), ('cash', 'Cash at Branch')], default='eps_transfer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='payments.customer')),
                ('statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments', to='payments.creditstatement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BNPLLoan',
        ),
    ]
